// <auto-generated />
using System;
using System.Net;
using DLR.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DLR.Server.Data.Migrations
{
    [DbContext(typeof(DlrDbContext))]
    [Migration("20260821012352_AddPrivateArea")]
    partial class AddPrivateArea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DLR.Server.Data.Comments.CommentReaction", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reaction");

                    b.HasKey("CommentId", "UserId")
                        .HasName("pk_comment_reaction");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_reaction_user_id");

                    b.ToTable("comment_reaction", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.Poll", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_multiple");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTimeOffset?>("ClosedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_utc");

                    b.Property<DateTimeOffset?>("ClosesUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_utc");

                    b.HasKey("CommentId")
                        .HasName("pk_poll");

                    b.HasIndex("ClosedByUserId")
                        .HasDatabaseName("ix_poll_closed_by_user_id");

                    b.ToTable("poll", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.PollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_poll_option");

                    b.HasIndex("CommentId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_poll_option_ordinal");

                    b.ToTable("poll_option", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.PollVote", b =>
                {
                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_option_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.HasKey("PollOptionId", "UserId")
                        .HasName("pk_poll_vote");

                    b.HasIndex("PollOptionId")
                        .HasDatabaseName("ix_poll_vote_option");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_poll_vote_user_id");

                    b.ToTable("poll_vote", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.RideComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ClientGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset?>("EditedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_utc");

                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<Guid?>("PinnedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("pinned_by_user_id");

                    b.Property<DateTimeOffset?>("PinnedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pinned_utc");

                    b.Property<DateTimeOffset>("PostedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_utc");

                    b.HasKey("Id")
                        .HasName("pk_ride_comment");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_ride_comment_author_id");

                    b.HasIndex("GroupRideId")
                        .HasDatabaseName("ix_ride_comment_pinned")
                        .HasFilter("is_pinned");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_ride_comment_photo_id");

                    b.HasIndex("GroupRideId", "PostedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ride_comment_ride_posted");

                    b.HasIndex("GroupRideId", "AuthorId", "ClientGuid")
                        .IsUnique()
                        .HasDatabaseName("ux_ride_comment_client");

                    b.ToTable("ride_comment", null, t =>
                        {
                            t.HasCheckConstraint("ck_ride_comment_has_content", "body IS NOT NULL OR photo_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<IPAddress>("CreatedByIp")
                        .HasColumnType("inet")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("InactivityWarnedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactivity_warned_utc");

                    b.Property<DateTimeOffset>("LastActiveUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_utc");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("MarkerColour")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("marker_colour");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<double?>("PrivateAreaLat")
                        .HasColumnType("double precision")
                        .HasColumnName("private_area_lat");

                    b.Property<double?>("PrivateAreaLon")
                        .HasColumnType("double precision")
                        .HasColumnName("private_area_lon");

                    b.Property<double?>("PrivateAreaRadiusM")
                        .HasColumnType("double precision")
                        .HasColumnName("private_area_radius_m");

                    b.Property<bool>("RequiresEmailConfirmation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_email_confirmation");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("ShareDisplayName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("share_display_name");

                    b.Property<bool>("ShareEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("share_email");

                    b.Property<bool>("SharePhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("share_phone_number");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("LastActiveUtc")
                        .HasDatabaseName("ix_users_last_active");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("CreatedByIp", "CreatedUtc")
                        .HasDatabaseName("ix_users_created_ip");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.DeletedAccountToken", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("DeletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_utc");

                    b.HasKey("TokenHash")
                        .HasName("pk_deleted_account_token");

                    b.HasIndex("DeletedUtc")
                        .HasDatabaseName("ix_deleted_account_token_deleted");

                    b.ToTable("deleted_account_token", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Mobile")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_user");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revoked_reason");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_utc");

                    b.Property<Guid?>("SuccessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("successor_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_refresh_token_device_id");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("ix_refresh_token_expires");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_token_family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_token_hash");

                    b.HasIndex("UserId", "DeviceId")
                        .HasDatabaseName("ix_refresh_token_user_device");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Markers.Marker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<short?>("DirectionDeg")
                        .HasColumnType("smallint")
                        .HasColumnName("direction_deg");

                    b.Property<Guid?>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("icon");

                    b.Property<int>("Lat")
                        .HasColumnType("integer")
                        .HasColumnName("lat");

                    b.Property<int>("Lon")
                        .HasColumnType("integer")
                        .HasColumnName("lon");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("title");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_marker");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_marker_created_by_user_id");

                    b.HasIndex("GroupRideId")
                        .HasDatabaseName("ix_marker_group_ride");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_marker_photo_id");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_marker_track");

                    b.HasIndex("GroupRideId", "CreatedByUserId")
                        .HasDatabaseName("ix_marker_ride_author");

                    b.ToTable("marker", null, t =>
                        {
                            t.HasCheckConstraint("ck_marker_one_parent", "(track_id IS NULL) <> (group_ride_id IS NULL)");
                        });
                });

            modelBuilder.Entity("DLR.Server.Data.Moderation.ContentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("ContentSnapshot")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content_snapshot");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_utc");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_kind");

                    b.HasKey("Id")
                        .HasName("pk_content_report");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("ix_content_report_reported_by_user_id");

                    b.HasIndex("ResolvedUtc")
                        .HasDatabaseName("ix_content_report_unresolved")
                        .HasFilter("resolved_utc IS NULL");

                    b.HasIndex("TargetKind", "TargetId", "ReportedByUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_content_report_reporter");

                    b.ToTable("content_report", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Moderation.UserBlock", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.HasKey("BlockerId", "BlockedId")
                        .HasName("pk_user_block");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_user_block_blocked_id");

                    b.HasIndex("BlockerId")
                        .HasDatabaseName("ix_user_block_blocker");

                    b.ToTable("user_block", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Photos.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_ref");

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer")
                        .HasColumnName("height_px");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ThumbBlobRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("thumb_blob_ref");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer")
                        .HasColumnName("width_px");

                    b.HasKey("Id")
                        .HasName("pk_photo");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_photo_owner");

                    b.ToTable("photo", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Positions.RiderPosition", b =>
                {
                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short?>("AccuracyM")
                        .HasColumnType("smallint")
                        .HasColumnName("accuracy_m");

                    b.Property<short?>("HeadingDeg")
                        .HasColumnType("smallint")
                        .HasColumnName("heading_deg");

                    b.Property<int>("Lat")
                        .HasColumnType("integer")
                        .HasColumnName("lat");

                    b.Property<int>("Lon")
                        .HasColumnType("integer")
                        .HasColumnName("lon");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_utc");

                    b.Property<short?>("SpeedMps")
                        .HasColumnType("smallint")
                        .HasColumnName("speed_mps");

                    b.HasKey("GroupRideId", "UserId")
                        .HasName("pk_rider_position");

                    b.HasIndex("RecordedUtc")
                        .HasDatabaseName("ix_rider_position_recorded");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_rider_position_user_id");

                    b.ToTable("rider_position", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowMemberComments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_member_comments");

                    b.Property<bool>("AllowMemberMarkers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_member_markers");

                    b.Property<bool>("AllowMemberPhotos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_member_photos");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_utc");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("join_code");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("join_policy");

                    b.Property<int>("MemberCap")
                        .HasColumnType("integer")
                        .HasColumnName("member_cap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("SharingEndsUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sharing_ends_utc");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_group_ride");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ux_group_ride_join_code");

                    b.HasIndex("OwnerId", "CreatedUtc")
                        .HasDatabaseName("ix_group_ride_owner_created");

                    b.ToTable("group_ride", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<DateTimeOffset?>("DecidedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_utc");

                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RequestedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_group_ride_join_request");

                    b.HasIndex("GroupRideId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_join_request_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("UserId", "RequestedUtc")
                        .HasDatabaseName("ix_join_request_user_requested");

                    b.ToTable("group_ride_join_request", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideMember", b =>
                {
                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<bool>("ShareLocation")
                        .HasColumnType("boolean")
                        .HasColumnName("share_location");

                    b.HasKey("GroupRideId", "UserId")
                        .HasName("pk_group_ride_member");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_ride_member_user");

                    b.ToTable("group_ride_member", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideRoute", b =>
                {
                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_utc");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("GroupRideId", "TrackId")
                        .HasName("pk_group_ride_route");

                    b.HasIndex("AddedByUserId")
                        .HasDatabaseName("ix_group_ride_route_added_by_user_id");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_group_ride_route_track");

                    b.HasIndex("GroupRideId", "Position")
                        .HasDatabaseName("ix_group_ride_route_ride_position");

                    b.ToTable("group_ride_route", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AscentM")
                        .HasColumnType("double precision")
                        .HasColumnName("ascent_m");

                    b.Property<string>("BlobRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_ref");

                    b.Property<double>("BoundsMaxLat")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_max_lat");

                    b.Property<double>("BoundsMaxLon")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_max_lon");

                    b.Property<double>("BoundsMinLat")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_min_lat");

                    b.Property<double>("BoundsMinLon")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_min_lon");

                    b.Property<Guid>("ClientGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<double>("DistanceM")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_m");

                    b.Property<double?>("DurationS")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_s");

                    b.Property<DateTimeOffset?>("EditedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_utc");

                    b.Property<DateTimeOffset?>("EndedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_utc");

                    b.Property<string>("ImportedFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("imported_file_name");

                    b.Property<string>("ImportedFormat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("imported_format");

                    b.Property<bool>("IsFullyUploaded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fully_uploaded");

                    b.Property<double?>("MaxSpeedMps")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed_mps");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("segment_count");

                    b.Property<byte[]>("SimplifiedPolyline")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("simplified_polyline");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_track");

                    b.HasIndex("OwnerId", "ClientGuid")
                        .IsUnique()
                        .HasDatabaseName("ux_track_owner_client");

                    b.HasIndex("OwnerId", "ContentHash")
                        .HasDatabaseName("ix_track_owner_content_hash");

                    b.HasIndex("OwnerId", "CreatedUtc")
                        .HasDatabaseName("ix_track_owner_created");

                    b.ToTable("track", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.TrackRevision", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("BlobRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_ref");

                    b.Property<DateTimeOffset>("PurgeAfterUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_after_utc");

                    b.Property<DateTimeOffset>("ReplacedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TrackId")
                        .HasName("pk_track_revision");

                    b.HasIndex("PurgeAfterUtc")
                        .HasDatabaseName("ix_track_revision_purge_after");

                    b.ToTable("track_revision", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.CommentReaction", b =>
                {
                    b.HasOne("DLR.Server.Data.Comments.RideComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_reaction_ride_comment_comment_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_reaction_asp_net_users_user_id");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.Poll", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "ClosedBy")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_poll_asp_net_users_closed_by_user_id");

                    b.HasOne("DLR.Server.Data.Comments.RideComment", "Comment")
                        .WithOne()
                        .HasForeignKey("DLR.Server.Data.Comments.Poll", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_ride_comment_comment_id");

                    b.Navigation("ClosedBy");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.PollOption", b =>
                {
                    b.HasOne("DLR.Server.Data.Comments.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_option_poll_comment_id");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.PollVote", b =>
                {
                    b.HasOne("DLR.Server.Data.Comments.PollOption", "Option")
                        .WithMany("Votes")
                        .HasForeignKey("PollOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_vote_poll_option_poll_option_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_vote_asp_net_users_user_id");

                    b.Navigation("Option");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.RideComment", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ride_comment_asp_net_users_author_id");

                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany()
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ride_comment_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Photos.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ride_comment_photo_photo_id");

                    b.Navigation("Author");

                    b.Navigation("Photo");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.Device", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.RefreshToken", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_device_device_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_asp_net_users_user_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DLR.Server.Data.Markers.Marker", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_marker_asp_net_users_created_by_user_id");

                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany()
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_marker_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Photos.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_marker_photo_photo_id");

                    b.HasOne("DLR.Server.Data.Tracks.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_marker_track_track_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Photo");

                    b.Navigation("Ride");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DLR.Server.Data.Moderation.ContentReport", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_report_asp_net_users_reported_by_user_id");

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("DLR.Server.Data.Moderation.UserBlock", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Blocked")
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_asp_net_users_blocked_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_asp_net_users_blocker_id");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("DLR.Server.Data.Photos.Photo", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photo_asp_net_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DLR.Server.Data.Positions.RiderPosition", b =>
                {
                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany()
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rider_position_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rider_position_asp_net_users_user_id");

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRide", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_asp_net_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideJoinRequest", b =>
                {
                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany()
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_join_request_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_join_request_asp_net_users_user_id");

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideMember", b =>
                {
                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany("Members")
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_member_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_member_asp_net_users_user_id");

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideRoute", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_route_asp_net_users_added_by_user_id");

                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany("Routes")
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_route_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Tracks.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_route_track_track_id");

                    b.Navigation("AddedBy");

                    b.Navigation("Ride");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.Track", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_asp_net_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.TrackRevision", b =>
                {
                    b.HasOne("DLR.Server.Data.Tracks.Track", "Track")
                        .WithOne()
                        .HasForeignKey("DLR.Server.Data.Tracks.TrackRevision", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_revision_track_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.Poll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("DLR.Server.Data.Comments.PollOption", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRide", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
