@echo off
setlocal enabledelayedexpansion
rem ===========================================================================
rem  Create-AndroidUploadKey.bat
rem
rem  One-shot creation of the Google Play *upload* key (Documentation/store-release.md).
rem  Run this ONCE, ever. It refuses to overwrite an existing keystore, because
rem  a silently regenerated upload key is indistinguishable from a lost one until
rem  Play rejects the next bundle.
rem
rem  This is the UPLOAD key, not the app signing key. With Play App Signing
rem  enrolled, Google holds the app signing key and this one is resettable by
rem  support if it is lost. Without that enrolment, losing this file ends the
rem  app's update path permanently -- see section 14.2.
rem
rem  Nothing this script produces may enter source control. See the answer at the
rem  bottom of Documentation/store-release.md.
rem ===========================================================================

set "SIGNDIR=%USERPROFILE%\.dlr-signing"
set "KEYSTORE=%SIGNDIR%\dlr-upload.jks"
set "ALIAS=dlr-upload"
set "ENVFILE=%SIGNDIR%\dlr-signing-env.bat"

rem --- Locate keytool -------------------------------------------------------
set "KEYTOOL="
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\keytool.exe" set "KEYTOOL=%JAVA_HOME%\bin\keytool.exe"
if not defined KEYTOOL for /f "delims=" %%K in ('where keytool 2^>nul') do if not defined KEYTOOL set "KEYTOOL=%%K"
if not defined KEYTOOL for /d %%D in ("%ProgramFiles%\Android\openjdk\jdk-*") do if exist "%%D\bin\keytool.exe" set "KEYTOOL=%%D\bin\keytool.exe"
if not defined KEYTOOL for /d %%D in ("%ProgramFiles%\Microsoft\jdk-*") do if exist "%%D\bin\keytool.exe" set "KEYTOOL=%%D\bin\keytool.exe"
if not defined KEYTOOL (
	echo ERROR: keytool.exe not found. Install the Android SDK's OpenJDK or set JAVA_HOME.
	exit /b 1
)
echo Using keytool: %KEYTOOL%

rem --- Refuse to clobber ----------------------------------------------------
if exist "%KEYSTORE%" (
	echo.
	echo ERROR: %KEYSTORE% already exists.
	echo.
	echo This script will not overwrite it. Every build Play has ever accepted was
	echo signed with that file; a replacement is a different key and Play will
	echo reject bundles signed with it.
	echo.
	echo If you genuinely need a new upload key, request an upload key reset in the
	echo Play Console first, then move the old file aside by hand.
	exit /b 1
)

if not exist "%SIGNDIR%" mkdir "%SIGNDIR%"

rem --- Collect passwords without echoing them -------------------------------
echo.
echo Creating the Play upload key at:
echo   %KEYSTORE%
echo.
echo Choose a strong password and store it in your password manager NOW -- there
echo is no recovery path for a forgotten keystore password.
echo.

for /f "delims=" %%P in ('powershell -NoProfile -Command "$p=Read-Host -AsSecureString 'Keystore password (min 6 chars)'; [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($p))"') do set "STOREPASS=%%P"
for /f "delims=" %%P in ('powershell -NoProfile -Command "$p=Read-Host -AsSecureString 'Confirm keystore password'; [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($p))"') do set "STOREPASS2=%%P"

if not "%STOREPASS%"=="%STOREPASS2%" (
	echo ERROR: passwords do not match.
	exit /b 1
)
if "%STOREPASS%"=="" (
	echo ERROR: empty password.
	exit /b 1
)

rem --- Generate -------------------------------------------------------------
rem  RSA 4096, 10000 days. Play requires the upload key to stay valid past
rem  22 Oct 2033; 10000 days from today clears that by a wide margin.
"%KEYTOOL%" -genkeypair ^
	-v ^
	-keystore "%KEYSTORE%" ^
	-storetype PKCS12 ^
	-alias %ALIAS% ^
	-keyalg RSA ^
	-keysize 4096 ^
	-validity 10000 ^
	-storepass "%STOREPASS%" ^
	-keypass "%STOREPASS%" ^
	-dname "CN=Dumb Luck Routes, O=SecureHub, C=AU"

if errorlevel 1 (
	echo ERROR: keytool failed.
	exit /b 1
)

rem --- Write the environment file the publish script reads ------------------
rem  PKCS12 keeps one password for the store and the key. They are written as
rem  two variables because the csproj asks for both.
>  "%ENVFILE%" echo @echo off
>> "%ENVFILE%" echo rem Signing material for the DLR Android release build.
>> "%ENVFILE%" echo rem Generated by Create-AndroidUploadKey.bat. NEVER copy this into the repo.
>> "%ENVFILE%" echo set "DLR_ANDROID_KEYSTORE=%KEYSTORE%"
>> "%ENVFILE%" echo set "DLR_ANDROID_KEYSTORE_PASS=%STOREPASS%"
>> "%ENVFILE%" echo set "DLR_ANDROID_KEY_ALIAS=%ALIAS%"
>> "%ENVFILE%" echo set "DLR_ANDROID_KEY_PASS=%STOREPASS%"

rem  Owner-only ACL. The default profile ACL is already owner+SYSTEM+Admins, but
rem  inheritance from a re-permissioned %USERPROFILE% is not something to assume
rem  for a file that cannot be rotated.
icacls "%KEYSTORE%" /inheritance:r /grant:r "%USERNAME%:(R,W)" >nul 2>&1
icacls "%ENVFILE%"  /inheritance:r /grant:r "%USERNAME%:(R,W)" >nul 2>&1

set "STOREPASS="
set "STOREPASS2="

echo.
echo ===========================================================================
echo  Created:
echo    Keystore     %KEYSTORE%
echo    Alias        %ALIAS%
echo    Env file     %ENVFILE%   (contains the password -- treat as the key itself)
echo.
echo  DO THIS NOW, before you forget:
echo    1. Record the password in your password manager.
echo    2. Copy both files to an ENCRYPTED offline backup (not OneDrive, not the
echo       repo, not email). Losing them with Play App Signing enrolled costs you
echo       a support ticket; losing them without it costs you the app.
echo    3. Enrol in Play App Signing on first upload if you have not already.
echo.
echo  Upload certificate fingerprints (Play Console may ask for these):
echo ===========================================================================
"%KEYTOOL%" -list -v -keystore "%KEYSTORE%" -alias %ALIAS% 2>nul | findstr /C:"SHA1:" /C:"SHA256:" /C:"Valid from"
echo.
echo  Next: run Publish-Android.bat
endlocal
