using Microsoft.Extensions.Logging;

namespace DLR.Server.Diagnostics;

/// <summary>
/// The one place server-side exceptions and significant events are recorded (§14.6).
/// <para>
/// A named class rather than an <c>ILogger&lt;T&gt;</c> at each call site, for two reasons. The
/// first is that the administration screen shows a *category* per line, and a hundred categories
/// each logging in their own words make a log that can be read but not scanned — everything worth
/// finding later goes through here and carries an area and an event id that can be grepped. The
/// second is that "significant" is a decision, not a level: an account created, a ride finished, a
/// nightly sweep deleting rows, a photograph rejected — these are ordinary successes that an
/// administrator reconstructing yesterday needs, and they are indistinguishable from chatter
/// unless something says which is which.
/// </para>
/// <para>
/// The methods are source-generated by <c>[LoggerMessage]</c>, so a call that will not be written
/// — the level is below <c>FileLog:MinimumLevel</c>, or logging is off — costs a branch rather
/// than a formatted string. That matters because this is called from the position path.
/// </para>
/// </summary>
/// <param name="logger">Writes to every registered provider, the log file among them.</param>
public sealed partial class ServerEvents(ILogger<ServerEvents> logger)
{
	/// <summary>
	/// The areas an event can belong to, spelled once.
	/// <para>
	/// A closed-ish list of short words rather than free text: the value's whole job is to make
	/// <c>Rides:</c> findable in a file that also contains everything else, and it cannot do that
	/// if half the call sites write "Ride" and the other half "rides".
	/// </para>
	/// </summary>
	public static class Areas
	{
		/// <summary>Booting, configuration, shutdown.</summary>
		public const string Startup = "Startup";

		/// <summary>Registration, sign-in, tokens, devices (§7).</summary>
		public const string Identity = "Identity";

		/// <summary>Group rides and the hub (§5.5).</summary>
		public const string Rides = "Rides";

		/// <summary>Photographs and their ingest (§15.2).</summary>
		public const string Photos = "Photos";

		/// <summary>Track import and export (§15.3).</summary>
		public const string Tracks = "Tracks";

		/// <summary>Reports, hiding, blocking (§13).</summary>
		public const string Moderation = "Moderation";

		/// <summary>The nightly job and anything else on a timer (§9).</summary>
		public const string Maintenance = "Maintenance";

		/// <summary>The administration screens themselves.</summary>
		public const string Admin = "Admin";

		/// <summary>Serving a request.</summary>
		public const string Request = "Request";
	}

	/// <summary>
	/// Something happened that an administrator reading the log later would want to know about,
	/// and nothing went wrong.
	/// </summary>
	/// <param name="area">One of <see cref="Areas"/>.</param>
	/// <param name="what">What happened, in a sentence, already past tense.</param>
	[LoggerMessage(EventId = 1000, Level = LogLevel.Information, Message = "{Area}: {What}")]
	public partial void Note(string area, string what);

	/// <summary>
	/// Something is not right but the server carried on — a retry that worked, a setting that is
	/// legal but probably not meant, a limit approached.
	/// </summary>
	/// <param name="area">One of <see cref="Areas"/>.</param>
	/// <param name="what">What is wrong and what was done about it.</param>
	[LoggerMessage(EventId = 1100, Level = LogLevel.Warning, Message = "{Area}: {What}")]
	public partial void Concern(string area, string what);

	/// <summary>
	/// An operation failed. The exception goes on the same line, flattened — see
	/// <see cref="FileLogger"/> for why a stack trace does not get forty lines of its own.
	/// </summary>
	/// <param name="area">One of <see cref="Areas"/>.</param>
	/// <param name="what">What was being attempted, not what the exception says.</param>
	/// <param name="exception">The failure.</param>
	[LoggerMessage(EventId = 1200, Level = LogLevel.Error, Message = "{Area}: {What}")]
	public partial void Failure(string area, string what, Exception exception);

	/// <summary>
	/// The server cannot do its job — a background service that has stopped, a dependency that has
	/// gone and is not coming back. Critical is for things somebody should be woken for.
	/// </summary>
	/// <param name="area">One of <see cref="Areas"/>.</param>
	/// <param name="what">What has stopped working.</param>
	/// <param name="exception">The failure.</param>
	[LoggerMessage(EventId = 1300, Level = LogLevel.Critical, Message = "{Area}: {What}")]
	public partial void Fatal(string area, string what, Exception exception);

	/// <summary>
	/// An exception that reached the top of a request (§14.6).
	/// <para>
	/// The path without its query string, deliberately: a query can carry a token, a shared-ride
	/// code or a search a rider typed, and none of those belong in a file an administrator reads
	/// months later. The reference is echoed to the caller, so a rider quoting the code from their
	/// error screen finds exactly one line here.
	/// </para>
	/// </summary>
	/// <param name="method">The HTTP verb.</param>
	/// <param name="path">The request path, without its query.</param>
	/// <param name="user">Who was signed in, or <c>anonymous</c>.</param>
	/// <param name="reference">The trace identifier the caller is shown.</param>
	/// <param name="exception">What was thrown.</param>
	[LoggerMessage(
		EventId = 1201,
		Level = LogLevel.Error,
		Message = "Request: unhandled {Method} {Path} for {User} [{Reference}]")]
	public partial void Unhandled(string method, string path, string user, string reference, Exception exception);

	/// <summary>
	/// An exception nobody was waiting for — a background thread, or a task whose result was never
	/// observed.
	/// <para>
	/// These are the ones worth having a log for at all. A request that throws produces a 500 that
	/// somebody notices; a hosted service that dies quietly produces a server that is up, answers
	/// every health check, and has silently stopped flushing positions.
	/// </para>
	/// </summary>
	/// <param name="where">What was running — the hook that caught it.</param>
	/// <param name="exception">What was thrown.</param>
	[LoggerMessage(EventId = 1301, Level = LogLevel.Critical, Message = "Unobserved failure in {Where}")]
	public partial void Unobserved(string where, Exception exception);
}
