// <auto-generated />
using System;
using System.Net;
using DLR.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DLR.Server.Data.Migrations
{
    [DbContext(typeof(DlrDbContext))]
    [Migration("20260801060620_AddSharingWindDown")]
    partial class AddSharingWindDown
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DLR.Server.Data.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<IPAddress>("CreatedByIp")
                        .HasColumnType("inet")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset>("LastActiveUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_utc");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<bool>("RequiresEmailConfirmation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_email_confirmation");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("ShareDisplayName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("share_display_name");

                    b.Property<bool>("ShareEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("share_email");

                    b.Property<bool>("SharePhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("share_phone_number");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("LastActiveUtc")
                        .HasDatabaseName("ix_users_last_active");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("CreatedByIp", "CreatedUtc")
                        .HasDatabaseName("ix_users_created_ip");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_user");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revoked_reason");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_utc");

                    b.Property<Guid?>("SuccessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("successor_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_refresh_token_device_id");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("ix_refresh_token_expires");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_token_family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_token_hash");

                    b.HasIndex("UserId", "DeviceId")
                        .HasDatabaseName("ix_refresh_token_user_device");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Positions.RiderPosition", b =>
                {
                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short?>("AccuracyM")
                        .HasColumnType("smallint")
                        .HasColumnName("accuracy_m");

                    b.Property<short?>("HeadingDeg")
                        .HasColumnType("smallint")
                        .HasColumnName("heading_deg");

                    b.Property<int>("Lat")
                        .HasColumnType("integer")
                        .HasColumnName("lat");

                    b.Property<int>("Lon")
                        .HasColumnType("integer")
                        .HasColumnName("lon");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_utc");

                    b.Property<short?>("SpeedMps")
                        .HasColumnType("smallint")
                        .HasColumnName("speed_mps");

                    b.HasKey("GroupRideId", "UserId")
                        .HasName("pk_rider_position");

                    b.HasIndex("RecordedUtc")
                        .HasDatabaseName("ix_rider_position_recorded");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_rider_position_user_id");

                    b.ToTable("rider_position", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_utc");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("join_code");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("join_policy");

                    b.Property<int>("MemberCap")
                        .HasColumnType("integer")
                        .HasColumnName("member_cap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("SharingEndsUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sharing_ends_utc");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_group_ride");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ux_group_ride_join_code");

                    b.HasIndex("OwnerId", "CreatedUtc")
                        .HasDatabaseName("ix_group_ride_owner_created");

                    b.ToTable("group_ride", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<DateTimeOffset?>("DecidedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_utc");

                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RequestedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_group_ride_join_request");

                    b.HasIndex("GroupRideId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_join_request_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("UserId", "RequestedUtc")
                        .HasDatabaseName("ix_join_request_user_requested");

                    b.ToTable("group_ride_join_request", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideMember", b =>
                {
                    b.Property<Guid>("GroupRideId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<bool>("ShareLocation")
                        .HasColumnType("boolean")
                        .HasColumnName("share_location");

                    b.HasKey("GroupRideId", "UserId")
                        .HasName("pk_group_ride_member");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_ride_member_user");

                    b.ToTable("group_ride_member", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AscentM")
                        .HasColumnType("double precision")
                        .HasColumnName("ascent_m");

                    b.Property<string>("BlobRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_ref");

                    b.Property<double>("BoundsMaxLat")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_max_lat");

                    b.Property<double>("BoundsMaxLon")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_max_lon");

                    b.Property<double>("BoundsMinLat")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_min_lat");

                    b.Property<double>("BoundsMinLon")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_min_lon");

                    b.Property<Guid>("ClientGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<double>("DistanceM")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_m");

                    b.Property<double?>("DurationS")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_s");

                    b.Property<DateTimeOffset?>("EditedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_utc");

                    b.Property<DateTimeOffset?>("EndedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_utc");

                    b.Property<string>("ImportedFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("imported_file_name");

                    b.Property<string>("ImportedFormat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("imported_format");

                    b.Property<bool>("IsFullyUploaded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fully_uploaded");

                    b.Property<double?>("MaxSpeedMps")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed_mps");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("segment_count");

                    b.Property<byte[]>("SimplifiedPolyline")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("simplified_polyline");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_track");

                    b.HasIndex("OwnerId", "ClientGuid")
                        .IsUnique()
                        .HasDatabaseName("ux_track_owner_client");

                    b.HasIndex("OwnerId", "ContentHash")
                        .HasDatabaseName("ix_track_owner_content_hash");

                    b.HasIndex("OwnerId", "CreatedUtc")
                        .HasDatabaseName("ix_track_owner_created");

                    b.ToTable("track", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.TrackRevision", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("BlobRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_ref");

                    b.Property<DateTimeOffset>("PurgeAfterUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_after_utc");

                    b.Property<DateTimeOffset>("ReplacedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TrackId")
                        .HasName("pk_track_revision");

                    b.HasIndex("PurgeAfterUtc")
                        .HasDatabaseName("ix_track_revision_purge_after");

                    b.ToTable("track_revision", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.Device", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Identity.RefreshToken", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_device_device_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_asp_net_users_user_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DLR.Server.Data.Positions.RiderPosition", b =>
                {
                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany()
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rider_position_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rider_position_asp_net_users_user_id");

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRide", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_asp_net_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideJoinRequest", b =>
                {
                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany()
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_join_request_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_join_request_asp_net_users_user_id");

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRideMember", b =>
                {
                    b.HasOne("DLR.Server.Data.Rides.GroupRide", "Ride")
                        .WithMany("Members")
                        .HasForeignKey("GroupRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_member_group_ride_group_ride_id");

                    b.HasOne("DLR.Server.Data.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_ride_member_asp_net_users_user_id");

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.Track", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_asp_net_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DLR.Server.Data.Tracks.TrackRevision", b =>
                {
                    b.HasOne("DLR.Server.Data.Tracks.Track", "Track")
                        .WithOne()
                        .HasForeignKey("DLR.Server.Data.Tracks.TrackRevision", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_revision_track_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DLR.Server.Data.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DLR.Server.Data.Rides.GroupRide", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
